from hackathon_utils.data_config import DATASET_NAME

CREATE_BENCHMARK_SUBMISSION = False
WEIGHTS_INITIALIZATION = "IMAGENET"
FILENAME = f"{DATASET_NAME}-results-{WEIGHTS_INITIALIZATION}-v4.csv"
OUTPUT_FOLDER_NAME = f"./segmentation_evaluation-{DATASET_NAME}-{WEIGHTS_INITIALIZATION}"
NUM_EPOCHS = 100
BATCH_SIZE = 8
PATIENCE = 10
ARCHITECTURE_NAME = "unetplusplus"
BACKBONE_NAME = "maxvit_tiny_tf_512.in1k"
WEIGHT_DECAY = 1e-4
LEARNING_RATE = 5e-4