from hackathon_utils.data_config import DATASET_NAME

WEIGHTS_INITIALIZATION = "IMAGENET"
OUTPUT_FOLDER_NAME = f"./segmentation_evaluation-{DATASET_NAME}-{WEIGHTS_INITIALIZATION}"

NUM_EPOCHS = 10
BATCH_SIZE = 8
PATIENCE = 10
ARCHITECTURE_NAME = "unetplusplus"
BACKBONE_NAME = "maxvit_tiny_tf_512.in1k"
WEIGHT_DECAY = 1e-4
LEARNING_RATE = 5e-4